# Generated by Django 5.2.6 on 2026-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_auto_delete_days_user_auto_delete_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_delete_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_delete_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='auto_empty_bin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_empty_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
