# Generated by Django 5.2.8 on 2026-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resource_last_used_user_is_focus_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
