# Generated by Django 5.2.8 on 2026-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folder_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resource_previews/'),
        ),
    ]
