# Generated by Django 5.2.8 on 2026-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resource_preview_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='preview_pdf',
        ),
    ]
