# Generated by Django 5.2.8 on 2026-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_resource_preview_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='converted_pdfs/'),
        ),
    ]
